### ISSUE TITLE
ruby-class-variables-and-class-methods-lab error

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#10]
When trying to fork this in Nitrous an error came up that said:

"learn.co says

Whoops! There was a problem opening this lab."

**Comment by AnnJohn** [comment]
hi @cmcmcmcm we recently switched from nitrous to a different development environment. For help getting it set up, you can use the "Ask a Question" feature and an expert will help you or you can email support@learn.co 

Thanks!

**Comment by ghost** [comment]
Cool, I emailed support and asked for a download link for the IDE as well as instructions.

Thanks!
Chris
