### ISSUE TITLE
Learn Atom does not have the correct tab or the assingment listed in the file tree

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#16]
Yesterday no tab displayed when I clicked on the Open link for the Class Variables and Methods Lab assignment. This evening there was a README.md tab but there was not text. I could not find the ruby-class-variables-and-class-methods-lab-v-000 under Labs tree either?
I do not know if this is a flatiron issue or the Learn.Atom tech support issue. 

Thanks,

Scott
![learn lesson 2](https://cloud.githubusercontent.com/assets/17987990/20583653/b7986556-b1a0-11e6-8625-04697c9505fb.gif)
![learn lesson](https://cloud.githubusercontent.com/assets/17987990/20583654/b79ed594-b1a0-11e6-8afa-d33b6aac1be7.gif)

**Comment by JeffKatzy** [comment]
Moving to learn issue.
