### ISSUE TITLE
issue with genre_count and artist_count tests

### ISSUE THREAD

**Issue by MartinCrane** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#17]
if I create an @@genre_count and @@artist_count class variable hash that gets updated each time a new object is created, my genre_count and artist_count class methods merely output the my hash rather than iterating over the artist and genre arrays and creating a new hash... 

so, within my Song initialize method is:

```
if @@genre_count.keys.include?(genre)
			@@genre_count[genre] += 1
		else
			@@genre_count[genre] = 1
		end
```

Learn doesn’t reset these class variables each time a test is given, so I get a failure on genre_count and artist_count that tally up each time an object is created through out the whole test process rather than just the specific genre_count and artist_count tests

**Comment by JeffKatzy** [comment]
This should be dynamically calculated by using the count method.
