### ISSUE TITLE
Lab not marked as complete

### ISSUE THREAD

**Issue by krystlebarnes** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#20]
I completed this lab a while back, but noticed that this lab is still not marked as complete with the green check mark in the drop down curriculum menu despite having passed the tests and submitted the pull request.

**Comment by drakeltheryuujin** [comment]
Hi @krystlebarnes, 

As mentioned in the referenced lesson, this would be considered a bug with the Learn platform. Please try the steps there and reopen this issue if it is not resolved, and you believe this to be an issue with the curriculum itself.

Thanks!
