### ISSUE TITLE
learn tests won't run until bundler gem installed

### ISSUE THREAD

**Issue by big32mike** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#21]
`learn open ruby-class-variables-and-class-methods-lab-online-web-pt-021119
Looking for lesson...
Forking lesson...
Cloning lesson...
Opening lesson...
Bundling...
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /home/incredible-form-
nd-class-methods-lab-online-web-pt-021119/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:302:in `activate_bin_path'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Done.
[16:29:30] (master) ruby-class-variables-and-class-methods-lab-online-web-pt-021119
// ♥ learn
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /home/incredible-form-
nd-class-methods-lab-online-web-pt-021119/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:302:in `activate_bin_path'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'`
Happens locally with the learn gem on my macbook, and via the learn ide (also running locally).

gem install bundler:2.0.1 worked in both cases

**Comment by maxwellbenton** [comment]
Hi @big32mike,

Thank you for opening this issue and providing feedback. Late last week we updated our IDE and a number of our lessons to use Ruby 2.6. It looks like this lesson's updated content was pushed before the official change. We apologize for any frustration this may have caused. We've updated set up instructions and gem requirements for our courses to use bundler 2.0.1 and Ruby 2.6 from now on, so this issue should be resolved for any future students.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
