### ISSUE TITLE
Object Remembrance could be introduced before students begin this lab 

### ISSUE THREAD

**Issue by coffeeexistence** [learn-co-curriculum/ruby-class-variables-and-class-methods-lab#6]
https://learn.co/tracks/full-stack-web-development/object-oriented-ruby/object-models/remembering-objects

I feel like the information in the "remembering-objects" lesson would give students more of a heads up before diving into the lab.

**Comment by AnnJohn** [comment]
thanks @coffeeexistence! we'll review this and change the order if need be.

**Comment by pletcher** [comment]
@SophieDeBenedetto @StevenNunez what do you think of shifting these lessons around?

We could probably just slot it in right before this lab?

**Comment by SophieDeBenedetto** [comment]
@pletcher yes I agree, let's move it.

**Comment by pletcher** [comment]
Done.
